// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iajkhhafkoqbdsnreoib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhamtoaGFma29xYmRzbnJlb2liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODY2NjgsImV4cCI6MjA2NTA2MjY2OH0.h8k5koh5QZDG2N7kPAcbT8EEviwAKkpCJldF_9MV-9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);